name: ChelsEsite

services:
  goldenafternoon-postgres:
    container_name: goldenafternoon-postgres
    image: postgres:17.2
    environment:
      POSTGRES_USER: chelsesite_user
      POSTGRES_PASSWORD: chelsesite_secret
      POSTGRES_DB: chelsesite_db
    networks: [goldenafternoon-network]
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: goldenafternoon-data
        target: /var/lib/postgresql/data

networks:
  goldenafternoon-network:
    name: goldenafternoon-network

volumes:
  goldenafternoon-data:
